In [1]:
import numpy as np
import sklearn.cluster as clr

In [2]:
rng = np.random.default_rng(3985)

## API Usage

In [49]:
N_CLRS = 3
N_FEATS = 3
N_PTS = 10

In [50]:
points = rng.integers(0, 10, [N_PTS, N_FEATS])
points

array([[1, 4, 8],
       [6, 0, 0],
       [7, 2, 6],
       [8, 4, 8],
       [1, 3, 9],
       [5, 7, 5],
       [6, 4, 2],
       [8, 5, 3],
       [7, 5, 8],
       [5, 7, 2]])

In [52]:
init_idxs = rng.integers(0, N_PTS, N_CLRS)
init_pts = points[init_idxs]
init_pts

array([[7, 2, 6],
       [5, 7, 2],
       [8, 5, 3]])

In [53]:
km = clr.KMeans(
    n_clusters=N_CLRS, init=init_pts, n_init=1, max_iter=300,
    random_state=3985, algorithm='lloyd', verbose=1
)

In [54]:
km.fit(points)

Initialization complete
Iteration 0, inertia 165.0.
Iteration 1, inertia 84.63333333333334.
Converged at iteration 1: strict convergence.


KMeans(init=array([[7, 2, 6],
       [5, 7, 2],
       [8, 5, 3]]),
       n_clusters=3, n_init=1, random_state=3985, verbose=1)

In [55]:
km.cluster_centers_

array([[4.8       , 3.6       , 7.8       ],
       [5.        , 7.        , 3.5       ],
       [6.66666667, 3.        , 1.66666667]])

## Test Determinism

In [82]:
N_FEATS = 1
points = rng.integers(0, 10, [N_CLRS, N_FEATS])
points *= 100
points = np.concatenate([points, points - 1, points + 1, points - 2, points + 2])
points

array([[400],
       [300],
       [100],
       [399],
       [299],
       [ 99],
       [401],
       [301],
       [101],
       [398],
       [298],
       [ 98],
       [402],
       [302],
       [102]])

In [83]:
N_PTS = points.shape[0]
init_pts = points[:N_CLRS, :]
init_pts

array([[400],
       [300],
       [100]])

### First Time

In [84]:
km = clr.KMeans(
    n_clusters=N_CLRS, init=init_pts, n_init=1, max_iter=300,
    random_state=3985, algorithm='lloyd', verbose=1
)
km.fit(points)

Initialization complete
Iteration 0, inertia 30.0.
Converged at iteration 0: center shift 8.077935669463161e-28 within tolerance 1.5557555555555558.


KMeans(init=array([[400],
       [300],
       [100]]), n_clusters=3, n_init=1,
       random_state=3985, verbose=1)

In [85]:
km.cluster_centers_

array([[400.],
       [300.],
       [100.]])

### Second Time

In [86]:
km = clr.KMeans(
    n_clusters=N_CLRS, init=init_pts, n_init=1, max_iter=300,
    random_state=3985, algorithm='lloyd', verbose=1
)
km.fit(points)

Initialization complete
Iteration 0, inertia 30.0.
Converged at iteration 0: center shift 8.077935669463161e-28 within tolerance 1.5557555555555558.


KMeans(init=array([[400],
       [300],
       [100]]), n_clusters=3, n_init=1,
       random_state=3985, verbose=1)

In [88]:
km.cluster_centers_

array([[400.],
       [300.],
       [100.]])

## Generate Testcases

In [53]:
N_PTS = 1024
N_FEATS = 128
N_CLRS = 8

In [54]:
points = rng.random([N_PTS, N_FEATS])
points

array([[0.56317041, 0.95547997, 0.18312246, ..., 0.24811908, 0.36786775,
        0.47234641],
       [0.54234708, 0.78222908, 0.36823254, ..., 0.14482314, 0.75532335,
        0.61035202],
       [0.43228993, 0.93069523, 0.69397088, ..., 0.76438538, 0.76332209,
        0.72476161],
       ...,
       [0.21329565, 0.49538786, 0.8798866 , ..., 0.83336527, 0.15184803,
        0.21125614],
       [0.07781889, 0.66145335, 0.30461088, ..., 0.8156401 , 0.66564087,
        0.90632432],
       [0.4581499 , 0.01187021, 0.62477843, ..., 0.79474108, 0.08554994,
        0.47615746]])

In [55]:
np.savetxt('tcase2.txt', points, fmt='%.8f', header=f'{N_PTS} {N_FEATS}')

In [56]:
init_idxs = rng.integers(0, N_PTS, N_CLRS)
init_idxs

array([414, 822, 844, 114, 551, 299, 363, 235])

In [57]:
np.savetxt('tcase2_cfg.txt', init_idxs, fmt='%d', header=f'{N_CLRS}')

In [58]:
km = clr.KMeans(
    n_clusters=N_CLRS, init=points[init_idxs], n_init=1, max_iter=300,
    random_state=3985, algorithm='lloyd', verbose=1
)
km.fit(points)

Initialization complete
Iteration 0, inertia 18957.27895195155.
Iteration 1, inertia 10628.102346552223.
Iteration 2, inertia 10591.752657807843.
Iteration 3, inertia 10574.047927286092.
Iteration 4, inertia 10563.121857697406.
Iteration 5, inertia 10555.615746436339.
Iteration 6, inertia 10551.849081694167.
Iteration 7, inertia 10548.228375788902.
Iteration 8, inertia 10546.484426903466.
Iteration 9, inertia 10545.101010073846.
Iteration 10, inertia 10543.771685159825.
Iteration 11, inertia 10543.606925631455.
Converged at iteration 11: strict convergence.


KMeans(init=array([[0.46844222, 0.54756619, 0.36111332, ..., 0.11239217, 0.15597298,
        0.17064516],
       [0.12981224, 0.97425168, 0.47519863, ..., 0.694163  , 0.0940981 ,
        0.42271824],
       [0.83902691, 0.20034395, 0.57073064, ..., 0.14460913, 0.45115221,
        0.07098355],
       ...,
       [0.15152029, 0.85397605, 0.47182507, ..., 0.32966771, 0.88295883,
        0.03751214],
       [0.48115509, 0.85586397, 0.6773574 , ..., 0.90053089, 0.01618376,
        0.81537324],
       [0.76866974, 0.69316588, 0.4171244 , ..., 0.17853811, 0.53892584,
        0.32082455]]),
       n_init=1, random_state=3985, verbose=1)

In [60]:
km.inertia_

10543.606925631455

### Simple Testcase

In [41]:
N_PTS = 10
N_CLRS = 3
N_FEATS = 2

In [42]:
points = rng.integers(0, 10, [N_CLRS, N_FEATS])
points *= 100
points = np.concatenate([points, points - 1, points + 1, points - 2, points + 2])
points

array([[300, 600],
       [300, 500],
       [500, 700],
       [299, 599],
       [299, 499],
       [499, 699],
       [301, 601],
       [301, 501],
       [501, 701],
       [298, 598],
       [298, 498],
       [498, 698],
       [302, 602],
       [302, 502],
       [502, 702]])

In [43]:
N_PTS = points.shape[0]
init_idxs = np.arange(N_CLRS)
init_idxs

array([0, 1, 2])

In [44]:
np.savetxt('tcase1.txt', points, fmt='%.8f', header=f'{N_PTS} {N_FEATS}')
np.savetxt('tcase1_cfg.txt', init_idxs, fmt='%d', header=f'{N_CLRS}')

In [45]:
km = clr.KMeans(
    n_clusters=N_CLRS, init=points[init_idxs], n_init=1, max_iter=300,
    random_state=3985, algorithm='lloyd', verbose=1
)
km.fit(points)

Initialization complete
Iteration 0, inertia 60.0.
Converged at iteration 0: center shift 0.0 within tolerance 0.7779777777777778.


KMeans(init=array([[300, 600],
       [300, 500],
       [500, 700]]),
       n_clusters=3, n_init=1, random_state=3985, verbose=1)

In [46]:
np.int32(km.cluster_centers_)

array([[300, 600],
       [300, 500],
       [500, 700]], dtype=int32)

In [50]:
np.savetxt('tcase1_gt.txt', km.cluster_centers_, fmt='%.8f', header=f'{N_CLRS} {N_FEATS}')

In [48]:
!cat tcase1_gt.txt

300.00000000 600.00000000
300.00000000 500.00000000
500.00000000 700.00000000


## Pairwise Squared Distance

$$
\begin{equation}
    \rho(R, Q) = (R^T)^2 I_{d \times n} + I_{m \times d} Q^2 - 2 R^T Q
    \begin{cases}
        R & d \times m \\
        Q & d \times n
    \end{cases}
\end{equation}
$$

In [3]:
import numpy as np

In [4]:
rng = np.random.default_rng(3985)

In [8]:
m = 2
n = 3
d = 4

In [9]:
R = rng.integers(0, 10, [d, m])
R

array([[8, 2],
       [7, 4],
       [9, 5],
       [6, 0]])

In [10]:
(np.ones([1, d]) @ R**2).T @ np.ones([1, n])

array([[230., 230., 230.],
       [ 45.,  45.,  45.]])

In [11]:
(R.T**2) @ np.ones([d, n])

array([[230., 230., 230.],
       [ 45.,  45.,  45.]])

In [12]:
Q = rng.integers(0, 10, [d, n])
Q

array([[2, 9, 4],
       [7, 5, 7],
       [7, 8, 9],
       [8, 0, 1]])

In [13]:
np.ones([m, d]) @ Q**2

array([[166., 170., 147.],
       [166., 170., 147.]])

In [14]:
2 * R.T @ Q

array([[352, 358, 336],
       [134, 156, 162]])

In [15]:
(R.T**2) @ np.ones([d, n]) + np.ones([m, d]) @ Q**2 - 2 * R.T @ Q

array([[44., 42., 41.],
       [77., 59., 30.]])

In [16]:
for i in range(m):
    for j in range(n):
        print(np.sum((R[:, i] - Q[:, j])**2))

44
42
41
77
59
30


### Memory-Optimized Version

In [17]:
sqr_norm_R = np.ones([1, d]) @ R**2
sqr_norm_R, sqr_norm_R.shape

(array([[230.,  45.]]), (1, 2))

In [18]:
sqr_norm_Q = np.ones([1, d]) @ Q**2
sqr_norm_Q, sqr_norm_Q.shape

(array([[166., 170., 147.]]), (1, 3))

#### Middle Term

In [25]:
stat = -2 * (R.T @ Q)
stat, stat.shape

(array([[-352, -358, -336],
        [-134, -156, -162]]),
 (2, 3))

#### Add Squared Norm of R

In [22]:
for j in range(n):
    for i in range(m):
        stat[i, j] = stat[i, j] + sqr_norm_R[0, i]
stat

array([[-122, -128, -106],
       [ -89, -111, -117]])

#### Add Squared Norm of Q

In [23]:
for i in range(m):
    for j in range(n):
        stat[i, j] = stat[i, j] + sqr_norm_Q[0, j]
stat

array([[44, 42, 41],
       [77, 59, 30]])

#### Optimized: Fused Add Squared Norms of R and Q

In [27]:
sqr_norm_R = np.ones([1, d]) @ R**2
sqr_norm_Q = np.ones([1, d]) @ Q**2
stat = -2 * (R.T @ Q)

for i in range(m):
    for j in range(n):
        stat[i, j] += sqr_norm_R[0, i] + sqr_norm_Q[0, j]
stat

array([[44, 42, 41],
       [77, 59, 30]])

## Matrix Version KMeans

### Library Version

In [1]:
import numpy as np
rng = np.random.default_rng(3985)

In [2]:
N_CTRS = 3
N_DIMS = 2

In [3]:
centers = rng.integers(0, 10, [N_CTRS, N_DIMS]) * 10
centers

array([[80, 70],
       [60, 70],
       [80, 90]])

In [4]:
points = np.concatenate([centers, centers - 1, centers + 1, centers - 2, centers + 2])
points

array([[80, 70],
       [60, 70],
       [80, 90],
       [79, 69],
       [59, 69],
       [79, 89],
       [81, 71],
       [61, 71],
       [81, 91],
       [78, 68],
       [58, 68],
       [78, 88],
       [82, 72],
       [62, 72],
       [82, 92]])

In [33]:
points.reshape(-1)

array([80, 70, 60, 70, 80, 90, 79, 69, 59, 69, 79, 89, 81, 71, 61, 71, 81,
       91, 78, 68, 58, 68, 78, 88, 82, 72, 62, 72, 82, 92])

In [5]:
N_PTS = N_CTRS * 5
init_idxs = np.arange(N_CTRS)
init_idxs

array([0, 1, 2])

In [6]:
from sklearn.cluster import KMeans
km = KMeans(
    n_clusters=N_CTRS, init=points[init_idxs], n_init=1, max_iter=300,
    random_state=3985, algorithm='lloyd', verbose=1
)
km.fit(points)

Initialization complete
Iteration 0, inertia 60.0.
Converged at iteration 0: center shift 0.0 within tolerance 0.009088888888888891.


KMeans(init=array([[80, 70],
       [60, 70],
       [80, 90]]), n_clusters=3,
       n_init=1, random_state=3985, verbose=1)

In [7]:
np.int32(km.cluster_centers_)

array([[80, 70],
       [60, 70],
       [80, 90]], dtype=int32)

### Matrix Version

In [6]:
def dim_info():
    print(f'N_PTS={N_PTS}, N_CTRS={N_CTRS}, N_DIMS={N_DIMS}')
dim_info()

N_PTS=15, N_CTRS=3, N_DIMS=2


In [7]:
C = centers.T
P = points.T
C.shape, P.shape

((2, 3), (2, 15))

#### Compute Pairwise Squared Norm

In [8]:
sqr_norm_c = np.ones([1, N_DIMS]) @ (C ** 2)
sqr_norm_p = np.ones([1, N_DIMS]) @ (P ** 2)
pw_sqr_norm = -2 * (C.T @ P)

for i in range(N_CTRS):
    for j in range(N_PTS):
        pw_sqr_norm[i, j] += sqr_norm_c[0, i] + sqr_norm_p[0, j]
pw_sqr_norm

array([[  0, 400, 400,   2, 442, 362,   2, 362, 442,   8, 488, 328,   8,
        328, 488],
       [400,   0, 800, 362,   2, 722, 442,   2, 882, 328,   8, 648, 488,
          8, 968],
       [400, 800,   0, 442, 882,   2, 362, 722,   2, 488, 968,   8, 328,
        648,   8]])

#### Find Mean Index

In [9]:
dim_info()
pw_sqr_norm.shape

N_PTS=15, N_CTRS=3, N_DIMS=2


(3, 15)

In [10]:
m_idxs = np.argmin(pw_sqr_norm, axis=0)
m_idxs

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

#### Create Summation Matrix

In [11]:
sum_m = np.zeros([N_PTS, N_CTRS])
for i in range(N_PTS):
    sum_m[i, m_idxs[i]] = 1.0
sum_m, sum_m.shape

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 (15, 3))

In [12]:
P

array([[80, 60, 80, 79, 59, 79, 81, 61, 81, 78, 58, 78, 82, 62, 82],
       [70, 70, 90, 69, 69, 89, 71, 71, 91, 68, 68, 88, 72, 72, 92]])

In [13]:
P @ sum_m

array([[400., 300., 400.],
       [350., 350., 450.]])

In [16]:
dim_info()

N_PTS=15, N_CTRS=3, N_DIMS=2


In [17]:
sum_m = np.ones([N_PTS, N_CTRS]) * -1
for i in range(N_PTS):
    for j in range(N_CTRS):
        sum_m[i, j] = 1.0 if j == m_idxs[i] else 0.0
sum_m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Create Cluster Size Matrix

In [18]:
dim_info()

N_PTS=15, N_CTRS=3, N_DIMS=2


In [19]:
cluster_size = np.zeros([N_CTRS])
for i in range(N_PTS):
    cluster_size[m_idxs[i]] += 1

cluster_size

array([5., 5., 5.])

In [84]:
dim_info()

N_PTS=15, N_CTRS=3, N_DIMS=2


In [87]:
P.shape, sum_m.shape, cluster_size.shape

((2, 15), (15, 3), (3,))

In [100]:
new_m = P @ sum_m
new_m

array([[ 50., 250., 400.],
       [250., 400.,   0.]])

In [101]:
for i in range(N_CTRS):
    for j in range(N_DIMS):
        new_m[j, i] = new_m[j, i] / cluster_size[i]
new_m

array([[10., 50., 80.],
       [50., 80.,  0.]])

#### Create Average Matrix

In [22]:
dim_info()

N_PTS=15, N_CTRS=3, N_DIMS=2


In [23]:
cluster_size = np.zeros([N_CTRS])
for i in range(N_PTS):
    cluster_size[m_idxs[i]] += 1

cluster_size

array([5., 5., 5.])

In [25]:
avg = np.ones([N_PTS, N_CTRS]) * -1
for i in range(N_PTS):
    for j in range(N_CTRS):
        avg[i, j] = 1.0 / cluster_size[j] if j == m_idxs[i] else 0.0
avg

array([[0.2, 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0.2],
       [0.2, 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0.2],
       [0.2, 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0.2],
       [0.2, 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0.2],
       [0.2, 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0.2]])

### Putting Everything Together

In [26]:
def matrix_kmeans(points, means, N_PTS, N_CTRS, N_DIMS):
    '''
    Inputs:
        points: [N_DIMS, N_PTS]
        means:  [N_DIMS, N_CTRS]
    Output:
        new_means: [N_DIMS, N_CTRS]
    '''
    # Compute squared norm for points and means (Matmul or kernel)
    eye_dim = np.ones([1, N_DIMS])
    sqr_norm_c = eye_dim @ (means ** 2)   # [1, N_CTRS]
    sqr_norm_p = eye_dim @ (points ** 2)  # [1, N_PTS]

    # Compute pairwise squared distance middle term (Matmul)
    pw_sqr_dist = -2 * (means.T @ points)  # [N_CTRS, N_PTS]

    # Add squared norm terms to pairwise squared distance (Kernel)
    for i in range(N_CTRS):
        for j in range(N_PTS):
            pw_sqr_dist[i, j] += sqr_norm_c[0, i] + sqr_norm_p[0, j]

    # Find index for minimum index (Matmul)
    m_idxs = np.argmin(pw_sqr_dist, axis=0)  # [1, N_PTS]

#     # Create summation matrix and count cluster_sizes (Kernel)
#     sum_m = np.zeros([N_PTS, N_CTRS])
#     cluster_sizes = np.zeros([N_CTRS])
#     for i in range(N_PTS):
#         sum_m[i, m_idxs[i]] = 1.0
#         cluster_sizes[m_idxs[i]] += 1

#     # Perform summation (Matmul)
#     new_means = points @ sum_m

#     # Average by cluster size (Kernel)
#     for i in range(N_CTRS):
#         for j in range(N_DIMS):
#             new_means[j, i] = new_means[j, i] / cluster_sizes[i]
    # Create average matrix
    cluster_size = np.zeros([N_CTRS])
    for i in range(N_PTS):
        cluster_size[m_idxs[i]] += 1
    avg = np.ones([N_PTS, N_CTRS]) * -1
    for i in range(N_PTS):
        for j in range(N_CTRS):
            avg[i, j] = 1.0 / cluster_size[j] if j == m_idxs[i] else 0.0
    new_means = points @ avg

    return new_means

In [27]:
matrix_kmeans(points.T, points[init_idxs].T, N_PTS, N_CTRS, N_DIMS)

array([[80., 60., 80.],
       [70., 70., 90.]])

In [14]:
np.int32(km.cluster_centers_).T

array([[80, 60, 80],
       [70, 70, 90]], dtype=int32)